export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const REGISTRATION_SUCCEEDED = 'REGISTRATION_SUCCEEDED';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const EDIT_REQUESTED = 'EDIT_REQUESTED';
export const EDIT_SUCCEEDED = 'EDIT_SUCCEEDED';
export const EDIT_FAILED = 'EDIT_FAILED';

export const USER_LIST_REQUESTED = 'USER_LIST_REQUESTED';
export const USER_LIST_SUCCEEDED = 'USER_LIST_SUCCEEDED';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const DEPARTMENT_LIST_REQUESTED = 'DEPARTMENT_LIST_REQUESTED';
export const DEPARTMENT_LIST_SUCCEEDED = 'DEPARTMENT_LIST_SUCCEEDED';
export const DEPARTMENT_LIST_FAILED = 'DEPARTMENT_LIST_FAILED';


/* Department */
export const CREATE_DEPARTMENT_REQUESTED = 'CREATE_DEPARTMENT_REQUESTED';
export const CREATE_DEPARTMENT_SUCCEEDED = 'CREATE_DEPARTMENT_SUCCEEDED';
export const CREATE_DEPARTMENT_FAILED = 'CREATE_DEPARTMENT_FAILED';

export const DELETE_DEPARTMENT_REQUESTED = 'DELETE_DEPARTMENT_REQUESTED';
export const DELETE_DEPARTMENT_SUCCEEDED = 'DELETE_DEPARTMENT_SUCCEEDED';
export const DELETE_DEPARTMENT_FAILED = 'DELETE_DEPARTMENT_FAILED';

export const EDIT_DEPARTMENT_REQUESTED = 'EDIT_DEPARTMENT_REQUESTED';
export const EDIT_DEPARTMENT_SUCCEEDED = 'EDIT_DEPARTMENT_SUCCEEDED';
export const EDIT_DEPARTMENT_FAILED = 'EDIT_DEPARTMENT_FAILED';

/* User */
export const CREATE_USER_REQUESTED = 'CREATE_USER_REQUESTED';
export const CREATE_USER_SUCCEEDED = 'CREATE_USER_SUCCEEDED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED';
export const EDIT_USER_SUCCEEDED = 'EDIT_USER_SUCCEEDED';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

/* Action Hisory */
export const ACTION_LOG_REQUESTED = 'ACTION_LOG_REQUESTED';
export const ACTION_LOG_SUCCEEDED = 'ACTION_LOG_SUCCEEDED';
export const ACTION_LOG_FAILED = 'ACTION_LOG_FAILED';