services:
  mongo1:
    hostname: mongo1
    image: mongo:4.2.23-bionic
    expose:
      - 27017
    ports:
      - 27017:27017 
    restart: always
    command: mongod --replSet rs0 --bind_ip_all
  mongo2:
    hostname: mongo2
    image: mongo:4.2.23-bionic
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    command: mongod --replSet rs0 --bind_ip_all
  mongoinit:
    image: mongo:4.2.23-bionic
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
    command: >
      mongo --host mongo1:27017 -eval
      '
      rs.initiate({
      "_id": "rs0",
      "members": [
        {
          "_id" : 0,
          "host" : "mongo1:27017",
          "priority" : 100
        },
        {
          "_id" : 1,
          "host" : "mongo2:27017",
          "priority" : 50
        }
      ]
      });
      rs.status();
      '